Document: ocaml-lua
Title: Debian ocaml-lua Manual
Author: <insert document author here>
Abstract: This manual describes what ocaml-lua is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ocaml-lua/ocaml-lua.sgml.gz

Format: postscript
Files: /usr/share/doc/ocaml-lua/ocaml-lua.ps.gz

Format: text
Files: /usr/share/doc/ocaml-lua/ocaml-lua.text.gz

Format: HTML
Index: /usr/share/doc/ocaml-lua/html/index.html
Files: /usr/share/doc/ocaml-lua/html/*.html
