#!/usr/bin/env python3
# This is free and unencumbered software released into the public domain.

from conreality import ddk

class Driver(ddk.Driver):
  """Driver for ...""" # TODO

  class ArgumentParser(ddk.ArgumentParser):
    def init(self):
      pass # TODO

  def init(self):
    pass # TODO

  def exit(self):
    pass # TODO

if __name__ == '__main__':
  import sys
  with Driver(argparser=Driver.ArgumentParser) as driver:
    sys.exit(driver.run())
