# .cma: Library of object bytecode
.cmo.cma:
	$(OCAMLC) -o $@ -a $(OCAMLCFLAGS) $^

# .cmo: Compiled object bytecode
.ml.cmo:
	$(OCAMLC) -o $@ -c $(OCAMLCFLAGS) $<

.ml.cmx:
	$(OCAMLOPT) -o $@ -c $(OCAMLCFLAGS) $<

# FIXME: this is too dangerous, overwriting manually-managed .mli files.
#.ml.mli:
#	$(OCAMLFIND) ocamlc -i $(OCAMLCFLAGS) $< > $@

# .cmi: Compiled interface
.mli.cmi:
	$(OCAMLC) -o $@ -c $(OCAMLCFLAGS) $<

.mll.ml:
	$(OCAMLLEX) -o $@ -q $<

# FIXME: this is too dangerous, overwriting manually-managed .mli files.
#%.mli: %.ml
#	$(OCAMLFIND) ocamlc -i $(OCAMLCFLAGS) $< > $@
