# .cma: Library of object bytecode
.cmo.cma:
	$(OCAMLC) -o $@ -a $(OCAMLCFLAGS) $^

# .cmo: Compiled object bytecode
.ml.cmo:
	$(OCAMLC) -o $@ -c $(OCAMLCFLAGS) $<

.ml.cmx:
	$(OCAMLOPT) -o $@ -c $(OCAMLCFLAGS) $<

.ml.mli:
	$(OCAMLFIND) ocamlc -i $(OCAMLCFLAGS) $< > $@

# .cmi: Compiled interface
.mli.cmi:
	$(OCAMLC) -o $@ -c $(OCAMLCFLAGS) $<

.mll.ml:
	$(OCAMLLEX) -o $@ -q $<
